---
services:
  pairdrop:
    image: lscr.io/linuxserver/pairdrop:1.10.9
    container_name: pairdrop
    environment:
      - PUID=1000
      - PGID=1000
      - DEBUG_MODE=true
      - "TZ={{ timezone }}"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pairdrop.rule=Host(`pairdrop.{{ domain }}`)"

networks:
  default:
    name: reverse-proxy
    external: true

