services:
  commafeed:
    image: athou/commafeed:4.6.0
    container_name: commafeed
    restart: unless-stopped
    environment:
      - "CF_APP_PUBLIC_URL=https://commafeed.{{ domain }}"
    volumes:
      - "{{ data_dir }}/{{ role_name }}/data:/commafeed/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.commafeed.rule=Host(`commafeed.{{ domain }}`)"

networks:
  default:
    name: reverse-proxy
    external: true

