---
- name: Deploy all public infrastructure services
  hosts: vps
  remote_user: debian
  roles:
    - role: geerlingguy.docker
      become: yes
      tags: [ dependencies ]
    - role: traefik
      tags: [ proxy ]
    - role: prometheus
      tags: [ monitoring, prometheus ]
    - role: commafeed
      tags: [ commafeed ]
    - role: pairdrop
    - role: diun
    - role: restic
    - role: grafana
      tags: [ monitoring ]
    - role: promtail
      tags: [ monitoring ]
    - role: uptime-kuma
    - role: ntfy

