---
services:
  promtail:
    container_name: promtail
    image: grafana/promtail:2.9.2
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - "{{ install_directory }}/{{ role_name }}/promtail.yml:/etc/promtail/promtail.yml"
      - "{{ data_dir }}/reverse-proxy/config/log/nginx/:/var/log/nginx/:ro"
  loki:
    container_name: loki
    image: grafana/loki:2.9.9
    user: "1000"
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - "{{ install_directory }}/{{ role_name }}/loki.yml:/etc/loki/loki.yml"

networks:
  default:
    name: reverse-proxy
    external: true

