services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - "TZ={{ timezone }}"
    user: 1000:1000
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 https://ntfy.foss.rizexor.com/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
    volumes:
      - "{{ data_dir }}/{{ role_name }}/cache:/var/cache/ntfy"
      - "{{ install_directory }}/{{ role_name }}/server.yml:/etc/ntfy/server.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntfy.rule=Host(`ntfy.{{ domain }}`)"

networks:
  default:
    name: reverse-proxy
    external: true

