services:
  ntfy:
    image: binwiederhier/ntfy:v2.11.0
    container_name: ntfy
    command:
      - serve
    environment:
      - "TZ={{ timezone }}"
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - "{{ data_dir }}/{{ role_name }}/cache:/var/cache/ntfy"
      - "{{ data_dir }}/{{ role_name }}/data:/var/lib/ntfy"
      - "{{ install_directory }}/{{ role_name }}/server.yml:/etc/ntfy/server.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntfy.rule=Host(`ntfy.{{ domain }}`)"

networks:
  default:
    name: reverse-proxy
    external: true

